---
- name: backup_client_workbook
  hosts: backup
  become: true

  tasks:

  - name: Create_backup_directory
    ansible.builtin.file:
     path: /mnt/backup
     state: directory
     mode: '0755'

  - name: Add_backup_disk
    community.general.parted:
      device: /dev/sdb
      number: 1
      state: present

  - name: Disk_formating
    filesystem:
      fstype: ext4
      dev: /dev/sdb1

  - name: Disk_mount
    mount:
      fstype: ext4
      src: /dev/sdb1
      path: /mnt/backup
      state: mounted

  - name: Empty /mnt/backup
    file:
      path: /mnt/backup/lost+found
      state: absent


  - name: Install_borgbackup
    apt:
      name: borgbackup
      state: present

  - name: Create a user 'borg' with a home directory
    ansible.builtin.user:
      name: borg
      password: "{{ '1234' | password_hash('sha256') }}"
      shell: /bin/bash
      create_home: yes

  - name: Change dir ownership
    ansible.builtin.file:
      path: /mnt/backup
      owner: borg
      group: borg
      mode: '0777'

  - name: Create .ssh directory
    ansible.builtin.file:
      path: /home/borg/.ssh
      owner: borg
      group: borg
      state: directory
      mode: '0700'

  - name: Create authorized_keys file
    file:
      path: "/home/borg/.ssh/authorized_keys"
      state: touch
      owner: borg
      group: borg
      mode: 0600

- hosts: client
  become: true

  tasks:

  - name: Install_borgbackup
    apt:
      name: borgbackup
      state: present

  - name: Copy_borg-backup.service
    copy:
      src: ./borg-backup.service
      dest: /etc/systemd/system/
      remote_src: no
      mode: 0644
      owner: root
      group: root

  - name: Copy_borg-backup.timer
    copy:
      src: ./borg-backup.timer
      dest: /etc/systemd/system/
      remote_src: no
      mode: 0644
      owner: root
      group: root

  - name: Create key for root
    ansible.builtin.user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /root/.ssh/id_rsa